In [1]:
!pip install torch

ModuleNotFoundError: No module named 'torch'

In [4]:
from __future__ import print_function
import torch

In [10]:
# 初期化しないと値はバラバラに
x = torch.empty(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4738, 0.5964, 0.6824],
        [0.7134, 0.3003, 0.0326],
        [0.1522, 0.4193, 0.7227],
        [0.1430, 0.1306, 0.5046],
        [0.8452, 0.8657, 0.8715]])


In [15]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [24]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2047,  1.8272, -1.0836],
        [-1.7062,  1.3481, -2.3612],
        [-0.7970,  0.1375,  0.1307],
        [ 0.7806, -0.7434,  0.7792],
        [ 1.7760, -0.7863,  0.2050]])


In [25]:
print(x.shape)
print(x.size())


torch.Size([5, 3])
torch.Size([5, 3])


In [26]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1761,  2.0925, -1.0603],
        [-1.3685,  1.7579, -1.7458],
        [-0.6246,  1.0586,  0.7204],
        [ 1.2610, -0.5802,  0.9026],
        [ 2.6919, -0.1647,  0.4457]])


In [27]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) # output先を指定
print(result)

tensor([[-0.1761,  2.0925, -1.0603],
        [-1.3685,  1.7579, -1.7458],
        [-0.6246,  1.0586,  0.7204],
        [ 1.2610, -0.5802,  0.9026],
        [ 2.6919, -0.1647,  0.4457]])


In [30]:

print(x)
print(y)
y.add_(x) # add_  値自体を置き換える
print(y)

tensor([[-0.2047,  1.8272, -1.0836],
        [-1.7062,  1.3481, -2.3612],
        [-0.7970,  0.1375,  0.1307],
        [ 0.7806, -0.7434,  0.7792],
        [ 1.7760, -0.7863,  0.2050]])
tensor([[0.0286, 0.2654, 0.0233],
        [0.3377, 0.4098, 0.6153],
        [0.1724, 0.9212, 0.5897],
        [0.4804, 0.1632, 0.1234],
        [0.9159, 0.6216, 0.2407]])
tensor([[-0.1761,  2.0925, -1.0603],
        [-1.3685,  1.7579, -1.7458],
        [-0.6246,  1.0586,  0.7204],
        [ 1.2610, -0.5802,  0.9026],
        [ 2.6919, -0.1647,  0.4457]])


In [32]:
x = torch.randn(4, 4)
y = x.view(16)   # viewでreshape    x自体は変化しないことに注意
z = x.view(-1, 8) # -1はよしなにやってねサイン

print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
# view()して作ったテンソルも同じメモリ空間を指しているので、yに値を入れるとxも変化する
x = torch.randn(4, 4)
print(x)
y = x.view(16)   
y[0:2] = 0

print(y)
print(x)

tensor([[ 1.1499,  0.7208, -1.1816, -0.3610],
        [ 1.4137,  0.4858, -0.2342, -0.3933],
        [-0.8618,  1.0866,  2.3717,  0.9323],
        [ 0.1567,  1.2658,  0.4764,  0.8672]])
tensor([ 0.0000,  0.0000, -1.1816, -0.3610,  1.4137,  0.4858, -0.2342, -0.3933,
        -0.8618,  1.0866,  2.3717,  0.9323,  0.1567,  1.2658,  0.4764,  0.8672])
tensor([[ 0.0000,  0.0000, -1.1816, -0.3610],
        [ 1.4137,  0.4858, -0.2342, -0.3933],
        [-0.8618,  1.0866,  2.3717,  0.9323],
        [ 0.1567,  1.2658,  0.4764,  0.8672]])


In [37]:
x = torch.randn(1)
print(x)
print(x.item()) # 普通のpythonの値を取り出す   値が一つだけの時しか使えない

tensor([0.0962])
0.09616874158382416


In [39]:
a = torch.ones(5)
print(a, type(a))

b = a.numpy() # numpyのarrayに変換
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [40]:
a.add_(1)
print(a)
print(b) # メモリを共有してるのでaを変えるとbも変化

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # numpy -> torch
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# GPUがある場合
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!