In [24]:
import torch

x =torch.ones(2, 2, requires_grad=True) # 勾配の計算が必要なときはフラグを立てる
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [25]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(y.grad_fn)

In [27]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [28]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad) # defaultはFalse
a.requires_grad_(True) # requires_grad_()でその変数のrequires_grad設定を変更できる
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [29]:
out.backward() # backpropagataion

scalarの場合は直接x.gradでアクセスできる

In [30]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [49]:
x = torch.randn(3, requires_grad=True)

y = x
print(y)
i = 0
while y.data.norm() < 1000:
    y = y * 2
    i += 1

print(y)
print(i)

tensor([-1.0934,  0.5043,  1.2446], requires_grad=True)
tensor([-1119.6000,   516.3875,  1274.4756], grad_fn=<MulBackward0>)
10


In [50]:
v = torch.tensor([1, .1, .1], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1024.0000,  102.4000,  102.4000])


In [47]:
2 ** 9

512